# Generated by Django 5.1.6 on 2025-02-18 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccionCrud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaractHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bateria', models.CharField(blank=True, max_length=45, null=True)),
                ('ram', models.CharField(blank=True, max_length=45, null=True)),
                ('ram_hz', models.IntegerField(blank=True, null=True)),
                ('grafica', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo_procesador', models.CharField(blank=True, max_length=45, null=True)),
                ('modelo_procesador', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo_almacenamiento', models.CharField(blank=True, max_length=45, null=True)),
                ('espacio_almacenamiento', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaractSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_anydesk', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dispositivo', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('disponibilidad', models.CharField(blank=True, max_length=45, null=True)),
                ('almacenamiento', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_estadoactivo', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_licencia', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion_licencia', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MantencionActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_mantencion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proceso', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_procesos', models.IntegerField(blank=True, null=True)),
                ('identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('ruta', models.CharField(blank=True, max_length=50, null=True)),
                ('archivo', models.CharField(blank=True, max_length=50, null=True)),
                ('levantamiento', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistemaoperativo', models.CharField(blank=True, max_length=45, null=True)),
                ('versionso', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_tiposervidor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_usuario', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(blank=True, max_length=40, null=True)),
                ('numero_factura', models.IntegerField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=45, null=True)),
                ('modelo', models.CharField(blank=True, max_length=45, null=True)),
                ('serie', models.CharField(max_length=50)),
                ('numero_modelo', models.CharField(blank=True, max_length=45, null=True)),
                ('disponibilidad', models.SmallIntegerField(blank=True, null=True)),
                ('estado_computador', models.IntegerField()),
                ('caract_hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.caracthardware')),
                ('caract_software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.caractsoftware')),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servidor', models.CharField(blank=True, max_length=45, null=True)),
                ('id_instancia', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_instancia', models.CharField(blank=True, max_length=45, null=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre_cuenta', models.CharField(blank=True, max_length=45, null=True)),
                ('ssh', models.SmallIntegerField(blank=True, null=True)),
                ('estado_usuario', models.CharField(blank=True, max_length=45, null=True)),
                ('llave', models.SmallIntegerField(blank=True, null=True)),
                ('estado_llave', models.CharField(blank=True, max_length=45, null=True)),
                ('servicios_aplicaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('proceso_servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.procesoservidor')),
                ('tipo_servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.tiposervidor')),
            ],
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_activo', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('computador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appweb.computador')),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appweb.dispositivo')),
                ('estado_activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appweb.estadoactivo')),
                ('licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appweb.licencia')),
                ('mantencion_activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appweb.mantencionactivo')),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appweb.servidor')),
            ],
        ),
        migrations.AddField(
            model_name='caractsoftware',
            name='sistema_operativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.sistemaoperativo'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('correo_tbk', models.CharField(blank=True, max_length=255, null=True)),
                ('llave_ssh', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Registroaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('accion_crud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.accioncrud')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.activo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.activo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.usuario')),
            ],
        ),
    ]
