# Generated by Django 5.1.6 on 2025-02-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computador',
            options={'verbose_name': 'Computador', 'verbose_name_plural': 'Computadores'},
        ),
    ]
