# Generated by Django 5.1.6 on 2025-02-18 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0002_alter_computador_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accioncrud',
            options={'verbose_name': 'Accion del Crud', 'verbose_name_plural': 'Acciones del Crud'},
        ),
        migrations.AlterModelOptions(
            name='asignacion',
            options={'verbose_name': 'Asignacion', 'verbose_name_plural': 'Asignaciones'},
        ),
        migrations.AlterModelOptions(
            name='caracthardware',
            options={'verbose_name': 'Caracteristica de Hardware', 'verbose_name_plural': 'Caracteristicas de Hardware'},
        ),
        migrations.AlterModelOptions(
            name='caractsoftware',
            options={'verbose_name': 'Caracteristica de Software', 'verbose_name_plural': 'Caracteristicas de Software'},
        ),
        migrations.AlterModelOptions(
            name='procesoservidor',
            options={'verbose_name': 'Proceso Servidor', 'verbose_name_plural': 'Proceso Servidores'},
        ),
        migrations.AlterModelOptions(
            name='registroaccion',
            options={'verbose_name': 'Registro Accion', 'verbose_name_plural': 'Registro Acciones'},
        ),
        migrations.AlterModelOptions(
            name='servidor',
            options={'verbose_name': 'Servidor', 'verbose_name_plural': 'Servidores'},
        ),
        migrations.AlterModelOptions(
            name='tiposervidor',
            options={'verbose_name': 'Tipo Servidor', 'verbose_name_plural': 'Tipos de Servidor'},
        ),
        migrations.AlterModelOptions(
            name='tipousuario',
            options={'verbose_name': 'Tipo de Usuario', 'verbose_name_plural': 'Tipos de Usuario '},
        ),
        migrations.AlterModelTable(
            name='accioncrud',
            table='ACCION_CRUD',
        ),
        migrations.AlterModelTable(
            name='activo',
            table='ACTIVO',
        ),
        migrations.AlterModelTable(
            name='asignacion',
            table='ASIGNACION',
        ),
        migrations.AlterModelTable(
            name='caracthardware',
            table='CARACT_HARDWARE',
        ),
        migrations.AlterModelTable(
            name='caractsoftware',
            table='CARACT_SOFTWARE',
        ),
        migrations.AlterModelTable(
            name='computador',
            table='COMPUTADOR',
        ),
        migrations.AlterModelTable(
            name='dispositivo',
            table='DISPOSITIVO',
        ),
        migrations.AlterModelTable(
            name='estadoactivo',
            table='ESTADO_ACTIVO',
        ),
        migrations.AlterModelTable(
            name='licencia',
            table='LICENCIA',
        ),
        migrations.AlterModelTable(
            name='mantencionactivo',
            table='MANTENCION_ACTIVO',
        ),
        migrations.AlterModelTable(
            name='procesoservidor',
            table='PROCESO_SERVIDOR',
        ),
        migrations.AlterModelTable(
            name='registroaccion',
            table='REGISTROACCION',
        ),
        migrations.AlterModelTable(
            name='servidor',
            table='SERVIDOR',
        ),
        migrations.AlterModelTable(
            name='sistemaoperativo',
            table='SISTEMA_OPERATIVO',
        ),
        migrations.AlterModelTable(
            name='tiposervidor',
            table='TIPO_SERVIDOR',
        ),
        migrations.AlterModelTable(
            name='tipousuario',
            table='TIPO_USUARIO',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='USUARIO',
        ),
    ]
