# Generated by Django 5.1.6 on 2025-02-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0003_alter_accioncrud_options_alter_asignacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sistemaoperativo',
            options={'verbose_name': 'Sistema Operativo', 'verbose_name_plural': 'Sistemas Operativos'},
        ),
    ]
